# Generated by GPT for demo data

from django.db import migrations


def seed_products(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    if Product.objects.exists():
        return

    Product.objects.bulk_create(
        [
            Product(name="Clavier mécanique", description="Switches tactiles, AZERTY", price="89.90"),
            Product(name="Souris gaming", description="Capteur haute précision", price="49.90"),
            Product(name="Écran 27 pouces", description="1440p, 144Hz", price="249.00"),
        ]
    )


def unseed_products(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(name__in=["Clavier mécanique", "Souris gaming", "Écran 27 pouces"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_products, reverse_code=unseed_products),
    ]

