apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: projet-sr
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "dev-insecure-secret-key-change-me"
  DB_USER: "projet_sr"
  DB_PASSWORD: "projet_sr"

